.\" $Xorg: makeg.man,v 1.4 2001/02/09 02:03:17 xorgcvs Exp $
.\" Copyright (c) 1996, 1998 The Open Group
.\" 
.\" Permission to use, copy, modify, distribute, and sell this software and its
.\" documentation for any purpose is hereby granted without fee, provided that
.\" the above copyright notice appear in all copies and that both that
.\" copyright notice and this permission notice appear in supporting
.\" documentation.
.\" 
.\" The above copyright notice and this permission notice shall be
.\" included in all copies or substantial portions of the Software.
.\" 
.\" THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
.\" EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
.\" MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
.\" IN NO EVENT SHALL THE OPEN GROUP BE LIABLE FOR ANY CLAIM, DAMAGES OR
.\" OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
.\" ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
.\" OTHER DEALINGS IN THE SOFTWARE.
.\" 
.\" Except as contained in this notice, the name of The Open Group shall
.\" not be used in advertising or otherwise to promote the sale, use or
.\" other dealings in this Software without prior written authorization
.\" from The Open Group.
.\"
.\"
.\" $XFree86: xc/config/util/makeg.man,v 1.2 2001/01/27 18:19:55 dawes Exp $
.\"
.TH MAKEG 1 __xorgversion__
.SH NAME
makeg \- make a debuggable executable
.SH SYNOPSIS
.B makeg
[
.I make-options .\|.\|.
] [
.I targets  .\|.\|.
]
.SH DESCRIPTION
The
.I makeg
script runs
.I make,
passing it variable settings to create a debuggable target when used
with a Makefile generated by
.I imake.
For example, it arranges for the C compiler to be called with the
.B \-g
option.
.SH ENVIRONMENT
.TP 8
.B MAKE
The
.I make
program to use.  Default ``make''.
.TP 8
.B GDB
Set to a non-null value if using the
.I gdb
debugger on Solaris 2, which requires additional debugging options to
be passed to the compiler.
.SH "SEE ALSO"
.I make (1),
.I imake (1)
