#!/bin/bash

PROJECT=freetype-2.10.4
FILE=$PROJECT.tar.gz
URL=http://download.savannah.gnu.org/releases/freetype
SRCDIR=`dirname $0`

. $SRCDIR/../../genpatch | filterdiff -p1 -x freetype2/CMakeLists.txt >$SRCDIR/turbovnc.patch
