#!/bin/bash

PROJECT=freetype-2.8.1
EXT=tar.gz
URL=http://download.savannah.gnu.org/releases/freetype
SRCDIR=`dirname $0`

. $SRCDIR/../../genpatch | filterdiff -p1 -x freetype2/CMakeLists.txt >$SRCDIR/turbovnc.patch
