LIBRARY xkbfile
VERSION LIBRARY_VERSION
EXPORTS
 XkbAccessXDetailText
 XkbActionText
 XkbActionTypeText
 XkbAtomGetString
 XkbAtomText
 XkbBehaviorText
 XkbCFAddModByName
 XkbCFAddPrivate
 XkbCFApplyMods
 XkbCFApplyRtrnValues
 XkbCFBindMods
 XkbCFDup
 XkbCFFree
 XkbCFFreeRtrn
 XkbCFParse
 XkbCFReportError
 XkbCFScan
 XkbChangeAtomDisplay
 XkbChangeKbdDisplay
 XkbConfigText
 XkbControlsMaskText
 XkbConvertGetByNameComponents
 XkbConvertXkbComponents
 XkbDetermineFileType
 XkbDoodadTypeText
 XkbEnsureSafeMapName
 XkbFindKeycodeByName
 XkbFreeOrderedDrawables
 XkbGeomFPText
 XkbGetOrderedDrawables
 XkbIMWhichStateMaskText
 XkbIndentText
 XkbInitAtoms
 XkbInternAtom
 XkbKeyNameText
 XkbKeysymText
 XkbLookupCanonicalRGBColor
 XkbLookupGroupAndLevel
 XkbMergeFile
 XkbModIndexText
 XkbModMaskText
 XkbNKNDetailMaskText
 XkbNameMatchesPattern
 XkbRF_AddGroup
 XkbRF_AddRule
 XkbRF_AddVarDesc
 XkbRF_AddVarDescCopy
 XkbRF_AddVarToDescribe
 XkbRF_Create
 XkbRF_Free
 XkbRF_GetComponents
 XkbRF_GetNamesProp
 XkbRF_Load
 XkbRF_LoadDescriptions
 XkbRF_LoadDescriptionsByName
 XkbRF_LoadRules
 XkbRF_LoadRulesByName
 XkbRF_SetNamesProp
 XkbReadFromServer
 XkbSIMatchText
 XkbStdBell
 XkbStdBellEvent
 XkbStringText
 XkbVModIndexText
 XkbVModMaskText
 XkbWriteCFile
 XkbWriteToServer
 XkbWriteXKBCompatMap
 XkbWriteXKBFile
 XkbWriteXKBGeometry
 XkbWriteXKBKeyTypes
 XkbWriteXKBKeycodes
 XkbWriteXKBKeymap
 XkbWriteXKBKeymapForNames
 XkbWriteXKBLayout
 XkbWriteXKBSemantics
 XkbWriteXKBSymbols
 XkbWriteXKMFile
 XkmFindTOCEntry
 XkmProbe
 XkmReadFile
 XkmReadFileSection
 XkmReadFileSectionName
 XkmReadTOC
#ifdef __UNIXOS2__
 _XkbStrCaseCmp
 XkbCFDflts
 _XkbErrLocation
 _XkbErrCode
 _XkbErrMessages
 _XkbKSCheckCase
#endif

/* $XFree86: xc/lib/xkbfile/xkbfile-def.cpp,v 1.1 2003/10/15 21:18:50 herrb Exp $ */
