# $Xorg: Makefile.ini,v 1.3 2000/08/17 19:41:52 cpqbld Exp $
#
# A way to get lndir built the first time, before you have imake up
# and running.  You may well have to specify OSFLAGS=-D<something> to
# get it to compile, which values are embedded in config files.  What
# you would pass as BOOTSTRAPCFLAGS might work.

OSFLAGS = 
CC = cc
CDEBUGFLAGS = -O
INCLUDES = -I.
CFLAGS = $(OSFLAGS) $(CDEBUGFLAGS) $(INCLUDES)
SHELL = /bin/sh
RM = rm -f
LN = ln -s

lndir:
	$(LN) ../../include X11
	$(CC) -o lndir $(CFLAGS) lndir.c
	$(RM) X11
