.\" $XFree86: xc/config/util/mergelib.man,v 1.2 2003/04/07 22:03:49 herrb Exp $
.\" shorthand for double quote that works everywhere.
.ds q \N'34'
.TH MERGELIB 1 __xorgversion__
.SH NAME
mergelib \- merge one library into another
.SH SYNOPSIS
.B mergelib
.I to-library
.I from-library
.RI [ object-filename-prefix ]
.SH DESCRIPTION
The
.I mergelib
program merges objects from one library into another.
The names of object files in
.I from-library
will be prefixed by
.I object-filename-prefix
(\*q_\*q by default) to avoid name clashes.
The merged library will be left in
.IR to-library .
.SH AUTHOR
Jim Fulton wrote the
.I mergelib
program for the X Consortium.
.PP
Colin Watson wrote this manual page, originally for the Debian Project.
