/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jcraft_jsch_agentproxy_usocket_JNIUSocketFactory */

#ifndef _Included_com_jcraft_jsch_agentproxy_usocket_JNIUSocketFactory
#define _Included_com_jcraft_jsch_agentproxy_usocket_JNIUSocketFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jcraft_jsch_agentproxy_usocket_JNIUSocketFactory
 * Method:    openSocket
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_jcraft_jsch_agentproxy_usocket_JNIUSocketFactory_openSocket
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_jcraft_jsch_agentproxy_usocket_JNIUSocketFactory
 * Method:    readSocket
 * Signature: (I[BI)I
 */
JNIEXPORT jint JNICALL Java_com_jcraft_jsch_agentproxy_usocket_JNIUSocketFactory_readSocket
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     com_jcraft_jsch_agentproxy_usocket_JNIUSocketFactory
 * Method:    writeSocket
 * Signature: (I[BI)V
 */
JNIEXPORT void JNICALL Java_com_jcraft_jsch_agentproxy_usocket_JNIUSocketFactory_writeSocket
  (JNIEnv *, jclass, jint, jbyteArray, jint);

/*
 * Class:     com_jcraft_jsch_agentproxy_usocket_JNIUSocketFactory
 * Method:    closeSocket
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_jcraft_jsch_agentproxy_usocket_JNIUSocketFactory_closeSocket
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
