/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jcraft_jsch_PageantConnector */

#ifndef _Included_com_jcraft_jsch_PageantConnector
#define _Included_com_jcraft_jsch_PageantConnector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jcraft_jsch_PageantConnector
 * Method:    queryPageant
 * Signature: (Lcom/jcraft/jsch/Buffer;)V
 */
JNIEXPORT void JNICALL Java_com_jcraft_jsch_PageantConnector_queryPageant
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
