#!/bin/sh

set -u
set -e
trap onexit INT
trap onexit TERM
trap onexit EXIT

TMPDIR=

onexit()
{
	if [ ! "$TMPDIR" = "" ]; then
		sudo rm -rf $TMPDIR
	fi
}

usage()
{
	echo "$0 <package name> <version> <build> <DEB architecture> <source dir.> <install dir. prefix>"
	exit 1
}

if [ $# -lt 6 ]; then usage $0; fi
PACKAGE_NAME=$1
VERSION=$2
BUILD=$3
DEBARCH=$4
SRCDIR=$5
PREFIX=$6

umask 022
rm -f $PACKAGE_NAME\_$DEBARCH.deb
TMPDIR=`mktemp -d /tmp/$PACKAGE_NAME-build.XXXXXX`
mkdir $TMPDIR/DEBIAN
cat $SRCDIR/deb-control.tmpl | sed s/{__PKGNAME}/$PACKAGE_NAME/g \
	| sed s/{__VERSION}/$VERSION/g | sed s/{__BUILD}/$BUILD/g \
	| sed s/{__ARCH}/$DEBARCH/g > $TMPDIR/DEBIAN/control

make install DESTDIR=$TMPDIR sysconfdir=/etc
make xserver-install DESTDIR=$TMPDIR sysconfdir=/etc

mkdir -p $TMPDIR/etc/init.d
cat vncserver.init | sed -e 's@vncserver :${display\%\%:@$PREFIX/bin/vncserver :${display\%\%:@g' | sed -e 's@vncserver -kill :${display\%\%:@$PREFIX/bin/vncserver -kill :${display\%\%:@g' > $TMPDIR/etc/init.d/tvncserver
chmod 755 $TMPDIR/etc/init.d/tvncserver

mkdir -p $TMPDIR/etc/sysconfig
install -m 644 tvncservers $TMPDIR/etc/sysconfig/tvncservers

mkdir -p $TMPDIR/usr/share/applications
cat > $TMPDIR/usr/share/applications/tvncviewer.desktop <<EOF
[Desktop Entry]
Name=TurboVNC Viewer
Comment=TurboVNC client application
Exec=$PREFIX/bin/vncviewer
Terminal=0
Type=Application
Categories=Application;Utility;X-Red-Hat-Extra;
EOF

mkdir -p $TMPDIR/usr/share/doc/$PACKAGE_NAME-$VERSION
install -m 644 $SRCDIR/LICENCE.TXT $TMPDIR/usr/share/doc/$PACKAGE_NAME-$VERSION
install -m 644 $SRCDIR/TurboVNC-ChangeLog.txt $TMPDIR/usr/share/doc/$PACKAGE_NAME-$VERSION
install -m 644 $SRCDIR/../vnc_docs/LICEN*.txt $SRCDIR/../vnc_docs/*.html $SRCDIR/../vnc_docs/*.png $SRCDIR/../vnc_docs/*.css $TMPDIR/usr/share/doc/$PACKAGE_NAME-$VERSION

sudo chown -Rh root:root $TMPDIR/*
dpkg -b $TMPDIR $PACKAGE_NAME\_$DEBARCH.deb

exit
