#!/bin/sh

set -u
set -e
trap onexit INT
trap onexit TERM
trap onexit EXIT

pkgtmpdir=

onexit()
{
	if [ ! "$pkgtmpdir" = "" ]; then
		sudo rm -rf $pkgtmpdir
	fi
}

usage()
{
	echo "$0 <package name> <version> <build> <source dir.> [universal]"
	exit 1
}

UNIVERSAL=0

if [ $# -lt 3 ]; then usage $0; fi
VERSION=$1
BUILD=$2
SRCDIR=$3
if [ $# -gt 3 ]; then
	if [ "$4" = "universal" ]; then UNIVERSAL=1; fi
fi

pkgname=TurboVNC
pkgtmpdir=`mktemp -d /tmp/$pkgname-build.XXXXXX`
PKGROOT=$pkgtmpdir/pkg/Package_Root
PACKAGEMAKER=/Developer/Applications/Utilities/PackageMaker.app/Contents/MacOS/PackageMaker

if [ -f $pkgname.dmg ]; then rm -f $pkgname.dmg; fi

umask 022
mkdir -p $PKGROOT/opt/$pkgname/bin
mkdir -p $PKGROOT/opt/$pkgname/man/man1
mkdir -p $PKGROOT/Applications/$pkgname
mkdir -p $PKGROOT/Library/Documentation/$pkgname
chmod 1775 $PKGROOT/Library
chmod 775 $PKGROOT/Library/Documentation 
mkdir -p $pkgtmpdir/pkg/Resources

install -m 755 vncviewer/vncviewer $PKGROOT/opt/$pkgname/bin/

if [ $UNIVERSAL = 1 ]; then
	if [ ! -d $SRCDIR/osxx86 ]; then
		mkdir -p $SRCDIR/osxx86
	fi
	pushd $SRCDIR/osxx86
	sh $SRCDIR/configure \
		CFLAGS='-isysroot /Developer/SDKs/MacOSX10.4u.sdk -mmacosx-version-min=10.4 -O3 -m32' \
		CXXFLAGS='-isysroot /Developer/SDKs/MacOSX10.4u.sdk -mmacosx-version-min=10.4 -O3 -m32' \
		LDFLAGS='-isysroot /Developer/SDKs/MacOSX10.4u.sdk -mmacosx-version-min=10.4 -m32'
	make
	popd
	lipo -create -arch i386 $SRCDIR/osxx86/vncviewer/vncviewer -arch x86_64 \
		$PKGROOT/opt/$pkgname/bin/vncviewer \
		-output $PKGROOT/opt/$pkgname/bin/vncviewer
fi

(cat $SRCDIR/Description.plist.tmpl | sed s/{__VERSION}/$VERSION/g > $pkgtmpdir/pkg/Description.plist)
(cat $SRCDIR/Info.plist.tmpl | sed s/{__VERSION}/$VERSION/g  | sed s/{__BUILD}/$BUILD/g > $pkgtmpdir/pkg/Info.plist)
install -m 755 $SRCDIR/uninstall.sh $PKGROOT/opt/$pkgname/bin/uninstall
install -m 644 $SRCDIR/vncviewer/vncviewer.man $PKGROOT/opt/$pkgname/man/man1/vncviewer.1
install -m 644 $SRCDIR/LICENCE.TXT $PKGROOT/Library/Documentation/$pkgname
install -m 644 $SRCDIR/TurboVNC-ChangeLog.txt $PKGROOT/Library/Documentation/$pkgname
install -m 644 $SRCDIR/../vnc_docs/LICEN*.txt $SRCDIR/../vnc_docs/*.html $SRCDIR/../vnc_docs/*.png $SRCDIR/../vnc_docs/*.css $PKGROOT/Library/Documentation/$pkgname
sudo ln -fs /Library/Documentation/$pkgname "$PKGROOT/Applications/$pkgname/Documentation"

sudo chown -R root:admin $PKGROOT 
cp $SRCDIR/License.rtf $SRCDIR/Welcome.rtf $SRCDIR/ReadMe.rtf $pkgtmpdir/pkg/Resources/ 
mkdir $pkgtmpdir/dmg
$PACKAGEMAKER -build -v -p $pkgtmpdir/dmg/$pkgname.pkg \
	-f $PKGROOT -r $pkgtmpdir/pkg/Resources \
	-i $pkgtmpdir/pkg/Info.plist -d $pkgtmpdir/pkg/Description.plist 
install -m 644 $SRCDIR/vncuninstall.applescript $pkgtmpdir 
sudo osacompile -t APPL -o "$pkgtmpdir/dmg/Uninstall $pkgname.app" $pkgtmpdir/vncuninstall.applescript 
sudo chown -R $USER "$pkgtmpdir/dmg/Uninstall $pkgname.app" 
hdiutil create -fs HFS+ -volname $pkgname-$VERSION \
	-srcfolder $pkgtmpdir/dmg $pkgtmpdir/$pkgname.dmg 
cp $pkgtmpdir/$pkgname.dmg .

exit 0
