#!/bin/bash

rm -rf rpms/
mkdir -p rpms/RPMS
cd rpms; ln -fs .. BUILD; cd ..

rpmbuild -bb --buildroot `pwd`/rpms/TurboVNC-buildroot --define "_topdir `pwd`/rpms" \
	--define "_bindir /opt/TurboVNC/bin" --define "_mandir /opt/TurboVNC/man" \
	--define "_datadir /opt/TurboVNC" turbovnc.spec
mv rpms/RPMS/i386/turbovnc*.rpm .
