#!/bin/bash

TARGET=
if [ `uname -m` = 'x86_64' ];then
	TARGET='--target i386'
fi

if [ "$1" = "clean" ]; then
xmkmf || exit -1
make clean || exit -1
cd Xvnc
if [ ! -f Makefile ]; then
	./configure || exit -1
fi
make clean || exit -1
cd ..
fi

xmkmf || exit -1
make World || exit -1
cd Xvnc
./configure || exit -1
make || exit -1
cd ..

umask 077
TMPDIR=`mktemp -d /tmp/vncbuild.XXXXXX`
mkdir -p $TMPDIR/rpms/RPMS
ln -fs `pwd` $TMPDIR/rpms/BUILD

BUILD=`date +%Y%m%d`
VERSION=`cat TurboVNC-version`
rpmbuild -bb --buildroot $TMPDIR/rpms/TurboVNC-buildroot --define "_topdir $TMPDIR/rpms" \
	--define "_bindir /opt/TurboVNC/bin" --define "_mandir /opt/TurboVNC/man" \
	--define "_datadir /opt/TurboVNC" --define "_version $VERSION" \
	--define "_build $BUILD" \
	$TARGET turbovnc.spec

mv $TMPDIR/rpms/RPMS/i386/turbovnc-$VERSION-$BUILD.i386.rpm turbovnc.i386.rpm

rm -rf $TMPDIR
