#!/bin/sh

if [ "$1" = "clean" ]; then
xmkmf || exit -1
make clean || exit -1
exit 0
fi

xmkmf || exit -1
make World || exit -1

pkgtmpdir=`mktemp -d /tmp/vncbuild.XXXXXX`
pkgname=TurboVNC
_VERSION=0.5
_BUILD=`date +%Y%m%d`
PACKAGEMAKER=/Developer/Applications/Utilities/PackageMaker.app/Contents/MacOS/PackageMaker

if [ -f $pkgname-$_VERSION.dmg ]; then rm -f $pkgname-$_VERSION.dmg; fi
mkdir -p $pkgtmpdir/pkg/Package_Root/opt/$pkgname/bin
mkdir -p $pkgtmpdir/pkg/Package_Root/opt/$pkgname/lib
mkdir -p $pkgtmpdir/pkg/Package_Root/opt/$pkgname/man/man1
mkdir -p $pkgtmpdir/pkg/Package_Root/Applications/$pkgname
mkdir -p $pkgtmpdir/pkg/Package_Root/Library/Documentation/$pkgname-$_VERSION
chmod 1775 $pkgtmpdir/pkg/Package_Root/Library
mkdir -p $pkgtmpdir/pkg/Resources
cat Description.plist.tmpl | sed s/{__VERSION}/$_VERSION/g > $pkgtmpdir/pkg/Description.plist
cat Info.plist.tmpl | sed s/{__VERSION}/$_VERSION/g  | sed s/{__BUILD}/$_BUILD/g > $pkgtmpdir/pkg/Info.plist
install -m 755 vncviewer/vncviewer $pkgtmpdir/pkg/Package_Root/opt/$pkgname/bin
install -m 755 /usr/lib/libturbojpeg-ipp.dylib $pkgtmpdir/pkg/Package_Root/opt/$pkgname/lib/libturbojpeg.dylib
install -m 755 /usr/lib/libturbojpeg-ipp.dylib $pkgtmpdir/pkg/Package_Root/opt/$pkgname/lib
install -m 755 /usr/lib/libturbojpeg-libjpeg.dylib $pkgtmpdir/pkg/Package_Root/opt/$pkgname/lib
install -m 755 /usr/bin/switchtjpeg $pkgtmpdir/pkg/Package_Root/opt/$pkgname/bin
install_name_tool -change libturbojpeg.dylib /opt/$pkgname/lib/libturbojpeg.dylib $pkgtmpdir/pkg/Package_Root/opt/$pkgname/bin/vncviewer
install -m 755 vncviewer/vncviewer.man $pkgtmpdir/pkg/Package_Root/opt/$pkgname/man/man1
install -m 644 ReadMe-MacApp.txt "$pkgtmpdir/pkg/Package_Root/Applications/$pkgname/Read Me.txt"
install -m 644 LICENCE.TXT $pkgtmpdir/pkg/Package_Root/Library/Documentation/$pkgname-$_VERSION
install -m 644 WhatsNew $pkgtmpdir/pkg/Package_Root/Library/Documentation/$pkgname-$_VERSION
install -m 644 TurboVNC-ChangeLog.txt $pkgtmpdir/pkg/Package_Root/Library/Documentation/$pkgname-$_VERSION
sudo chown -R root:admin $pkgtmpdir/pkg/Package_Root
cp License.rtf Welcome.rtf ReadMe.rtf $pkgtmpdir/pkg/Resources/
$PACKAGEMAKER -build -v -p $pkgtmpdir/$pkgname-$_VERSION.pkg \
	-f $pkgtmpdir/pkg/Package_Root -r $pkgtmpdir/pkg/Resources \
  -i $pkgtmpdir/pkg/Info.plist -d $pkgtmpdir/pkg/Description.plist
hdiutil create -fs HFS+ -volname $pkgname-$_VERSION \
	-srcfolder $pkgtmpdir/$pkgname-$_VERSION.pkg \
	$pkgtmpdir/$pkgname.dmg
cp $pkgtmpdir/$pkgname.dmg .
sudo rm -rf $pkgtmpdir
