'\" t
.\" ** The above line should force tbl to be a preprocessor **
.\" Man page for X vncviewer
.\"
.\" Copyright (C) 1998 Marcus.Brinkmann@ruhr-uni-bochum.de
.\" Copyright (C) 2000,2001 Red Hat, Inc.
.\" Copyright (C) 2001-2003 Constantin Kaplinsky <const@ce.cctpu.edu.ru>
.\"
.\" You may distribute under the terms of the GNU General Public
.\" License as specified in the file LICENCE.TXT that comes with the
.\" TurboVNC distribution.
.\"
.TH vncviewer 1 "December 2005" "" "TurboVNC"
.SH NAME
vncviewer \- an X11 viewer client for TurboVNC
.SH SYNOPSIS
.B vncviewer
.RI [\| options \|]
.RI [\| host \|][\| :display \|]
.br
.B vncviewer
.RI [\| options \|]
.RI [\| host \|][\| ::port \|]
.br
.B vncviewer
.RI [\| options \|]
.IR \-listen
.RI [\| display \|]
.br
.B vncviewer
.IR \-help
.br
.SH DESCRIPTION
.B vncviewer
is an Xt\-based client application for the VNC (Virtual Network
Computing) system. It can connect to any TurboVNC server, allowing
you to control the desktop environment of a different machine.

You can use F8 to display a pop\-up utility menu. Press F8 twice to
send an F8 keystroke to the remote system.
.SH OPTIONS
.TP
\fB\-help\fR
Prints a brief list of command line options.
.TP
\fB\-listen\fR
Start the viewer in "listen mode." The viewer will listen on port
5500+\fIdisplay_number\fR for reverse connections from a VNC server.
To connect to a listening viewer from a Windows VNC server, choose
"Add New Client..." from the TurboVNC Server's tray menu. To connect
to a listening viewer from a Unix/Linux VNC server, use the \fBvncconnect\fR
program.
.TP
\fB\-via\fR \fIgateway\fR
Automatically create an encrypted TCP tunnel to machine \fIgateway\fR,
then use that tunnel to connect to a VNC server running on \fIhost\fR. This option is specific
to TurboVNC or TightVNC. By default, this option invokes SSH local port
forwarding and assumes that the SSH client binary is located under
/usr/bin/ssh. Note that when using the \fB\-via\fR option, the \fIhost\fR
machine name should be specified from the point of view of the \fIgateway\fR
machine. For example, "localhost" denotes the \fIgateway\fR, not the
machine where vncviewer was launched. See the ENVIRONMENT section
below for information on configuring the \fB\-via\fR option.
.TP
\fB\-shared\fR
When connecting, request a shared session. In TurboVNC, this is the
default. When the session is shared, other users can connect to the
session (assuming they have the correct password) and collaborate with
the user who started the session.
.TP
\fB\-noshared\fR
When connecting, specify that the session may not be shared. If other
users are already connected to the session, then the TurboVNC server
(assuming it is configured using default settings) will deny any new
connections unless those connections request session sharing. In short, you will only be able to connect in
non-shared mode if no one else is connected to the session.
.TP
\fB\-viewonly\fR
Disable transfer of mouse and keyboard events from the client to the
server.
.TP
\fB\-fullscreen\fR
Start in full\-screen mode. Please be aware that operating in
full\-screen mode may confuse X window managers. Typically, such
conflicts cause incorrect handling of input focus or make the viewer
window disappear mysteriously. See the grabKeyboard setting in the
RESOURCES section below for a method to solve the input focus problem.
.TP
\fB\-noraiseonbeep\fR
By default, if an application running on the VNC server generates a
"bell" event, it will cause the VNC viewer window to restore itself
if it is minimized. Passing this option to the viewer causes it to
ignore remote bell events. This option is specific to TightVNC or
TurboVNC.
.TP
\fB\-user\fR \fIusername\fR
User name for Unix login authentication. Default is to use the current
Unix user name. If this option is given, then the viewer will use Unix
login authentication rather than the standard VNC authentication.
.TP
\fB\-passwd\fR \fIpasswd\-file\fR
File from which to get the VNC password (as generated by the
\fBvncpasswd\fR(1) program.) This option has no effect if Unix login
authentication is enabled.
.TP
\fB\-nocopyrect\fR
When a rectangular area on the server's display changes position
(such as when a window is moved), CopyRect encoding allows the server
to send only the coordinates of the new position rather than completely
re-sending the rectangular area. CopyRect encoding is enabled by default,
but this option disables it.
.TP
\fB\-subsamp \fI<0=None, 1=4:1:1, 2=4:2:2>\fR
Each pixel in a JPEG image is represented as a brightness (luminance)
value and a color (chrominance) value. Chrominance subsampling discards
every other chrominance value to reduce the image size, but it can
create visible compression artifacts. 4:1:1 subsampling provides the best
compression but also the lowest quality, since it discards every other
chrominance pixel along both X and Y. 4:2:2 subsampling discards every
other pixel along only the X direction.
.TP
\fB\-quality \fIlevel\fR
Use the specified JPEG quality \fIlevel\fR (1..100) to compress the
image of the remote desktop. Higher JPEG quality levels result in
less compression but better image quality.
.TP
\fB\-nocursorshape\fR
Normally, TurboVNC and TightVNC servers will send only changes to the
remote mouse cursor's shape and position. This results in the best mouse
responsiveness. Disabling cursor shape updates causes the server to
instead draw the mouse cursor and send it to the client as an image.
Disabling cursor shape updates can cause mouse movements to be painfully
slow, so do it only if something isn't working right.
.TP
\fB\-x11cursor\fR
Use a real X11 cursor with X-style cursor shape updates instead of
drawing the remote cursor on the framebuffer. This option also
disables the dot cursor and disables cursor position updates unless
the viewer is running in full\-screen mode.
.TP
\fB\-autopass\fR
Read a plain-text password from stdin. This option has no effect if
Unix login authentication is enabled.
.TP
\fB\-singlebuffer\fR
Normally, TurboVNC will wait until a window has finished redrawing
on the server before it redraws the window on the client. This is
called "double buffering", and it prevents tearing artifacts when
a 3D or video application switches frames. Disabling double
buffering makes TurboVNC behave more like other VNC implementations.
Normally, you shouldn't need to change this setting unless
something isn't working right.
.TP
\fB\-wan\fR
Enable protocol enhancements which will improve performance on
high-latency, low-bandwidth networks (e.g. broadband, T1.) These
optimizations will likely decrease TurboVNC's performance on fast
networks (e.g. Ethernet) and thus should not be used on such networks.
.TP
\fB\-broadband\fR
Preset for \fB\-wan -subsamp 1 -quality 30\fR.

This preset sets the JPEG quality to a relatively low level, which will
provide optimum performance on low-bandwidth connections by sacrificing
image quality. The "broadband" quality preset maintains a
usable image quality, but it will produce visible compression artifacts.
You may need to increase the quality if you are doing work that
requires a high level of detail. You can fine-tune the image quality
by using TurboVNC's F8 popup menu.
.SH RESOURCES
X resources that \fBvncviewer\fR knows about, aside from the
normal Xt resources, are as follows:
.TP
.B shareDesktop
Equivalent of the \fB\-shared\fR/\fB\-noshared\fR options. Default true.
.TP
.B viewOnly
Equivalent of the \fB\-viewonly\fR option. Default false.
.TP
.B fullScreen
Equivalent of the \fB\-fullscreen\fR option. Default false.
.TP
.B grabKeyboard
Grab keyboard in full-screen mode. This can help to solve problems
with losing keyboard focus. Default false.
.TP
.B raiseOnBeep
If set to false, this is the equivalent of the \fB\-noraiseonbeep\fR option. Default
true.
.TP
.B passwordFile
Equivalent of the \fB\-passwd\fR option.
.TP
.B userLogin
Equivalent of the \fB\-user\fR option.
.TP
.B passwordDialog
If true, vncviewer will pop up a dialog box to get the password. Otherwise,
it will get the password from the console. Irrelevant if \fBpasswordFile\fR
is set. Default false.
.TP
.B copyRect
If set to false, this is the equivalent of the \fB\-nocopyrect\fR option. Default
true. (TurboVNC\-specific)
.TP
.B compressLevel
Equivalent of the \fB\-subsamp\fR option (TurboVNC\-specific).
.TP
.B qualityLevel
Equivalent of the \fB\-quality\fR option (TurboVNC\-specific).
.TP
.B doubleBuffer
If set to false, this is the equivalent of the \fB\-singlebuffer\fR option. Default
true. (TurboVNC\-specific)
.TP
.B useRemoteCursor
If set to false, this is the equivalent of the \fB\-nocursorshape\fR option.
Default true. (TurboVNC\-specific)
.TP
.B useSharedMemory
Use the MIT shared memory extension if the viewer is running on the same machine as the VNC
server. Default true.
.TP
.B wmDecorationWidth, wmDecorationHeight
The total width and height taken up by window manager decorations.
This is used to calculate the maximum size of the VNC viewer window. 
Default width is 4, and default height is 24.
.TP
.B bumpScrollTime, bumpScrollPixels
When the viewer is in full\-screen mode and the VNC desktop is bigger
than the client's X display, scrolling will occur whenever the mouse
hits the edge of the screen. The maximum speed of scrolling is
bumpScrollPixels pixels every bumpScrollTime milliseconds. The actual
speed of scrolling will be slower than this, of course, depending on
how fast your machine is. Default is 20 pixels every 25 milliseconds.
.TP
.B popupButtonCount
The number of buttons in the popup window. See the README file for
more information on how to customize the buttons.
.TP
.B debug
For debugging. Default false.
.TP
.B rawDelay, copyRectDelay
For debugging, see the README file for details. Default 0 (off).
.SH ENVIRONMENT
When started with the \fB\-via\fR option, vncviewer reads the
\fBVNC_VIA_CMD\fR environment variable, expands patterns beginning
with the "%" character, and uses the resulting command line to
establish the secure tunnel to the VNC gateway. If \fBVNC_VIA_CMD\fR is not
set, this command line defaults to "/usr/bin/ssh -f -L %L:%H:%R %G sleep 20".

The following patterns are recognized in the \fBVNC_VIA_CMD\fR
environment (note that all of the patterns %G, %H, %L and %R must be present
in the command template):
.TP
.B %%
A literal "%";
.TP
.B %G
gateway machine name;
.TP
.B %H
remote VNC machine name, from the point of view of the gateway;
.TP
.B %L
local TCP port number;
.TP
.B %R
remote TCP port number.
.SH SEE ALSO
\fBvncserver\fR(1), \fBXvnc\fR(1), \fBvncpasswd\fR(1),
\fBvncconnect\fR(1), \fBssh\fR(1)
.SH AUTHORS
VNC was originally developed at AT&T Laboratories Cambridge. TightVNC
additions were implemented by Constantin Kaplinsky. TurboVNC, based
on TightVNC, is provided by The VirtualGL Project. Many other people
participated in development, testing and support.

\fBMan page authors:\fR
.br
Marcus Brinkmann <Marcus.Brinkmann@ruhr-uni-bochum.de>,
.br
Terran Melconian <terran@consistent.org>,
.br
Tim Waugh <twaugh@redhat.com>,
.br
Constantin Kaplinsky <const@ce.cctpu.edu.ru>
.br
Darrell Commander <dcommander@users.sourceforge.net>
